# -*- coding: utf-8 -*-
"""RAG_Pipeline_Improved.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tk-W-p-lmzkz87P3KyNiUn9p5BvEe-54

# Advanced RAG Pipeline — Attention Is All You Need

This notebook rebuilds the original RAG prototype with the improvements listed in the "Area of improvement" section:

1. **Chunking strategies** — structure-based, character-based, semantic
2. **Embedding model selection** — multilingual-aware, chunk-size-aware
3. **Query expansion** — for very short queries
4. **Retrieval strategies** — similarity, MMR, hybrid (BM25 + vector) with fallback
5. **Reranking** — cross-encoder reranker on top of retrieved candidates
6. **LLM experimentation** — compare instruction-following across models
7. **Caching** — exact-match cache + a lightweight semantic cache

> Run this in Colab (paths assume `/content/...`, same as the original notebook). Put the PDF at `/content/1706.03762v7.pdf` (upload it, or `!cp` from your Drive).

**Security note:** the original notebook had a live OpenAI API key hardcoded in a cell. That key should be treated as compromised and rotated. Below, the key is read from an environment variable / Colab secret instead — never commit real keys into a notebook.

## 0. Setup
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -U langchain langchain-community langchain-text-splitters langchain-experimental \
#     langchain-chroma langchain-huggingface langchain-openai \
#     sentence-transformers rank_bm25 langdetect chromadb tiktoken
#

import os
from getpass import getpass

# Prefer Colab's secret manager; fall back to a prompt. Never hardcode the key in the notebook.
try:
    from google.colab import userdata
    os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")
except Exception:
    if "OPENAI_API_KEY" not in os.environ:
        os.environ["OPENAI_API_KEY"] = getpass("Enter your OpenAI API key: ")

"""## 1. Load the document

Same loader as the original notebook.
"""

from langchain_community.document_loaders import PyPDFLoader

PDF_PATH = "/content/1706.03762v7.pdf"

loader = PyPDFLoader(file_path=PDF_PATH)
docs = loader.load()
print(f"Loaded {len(docs)} pages")

"""## 2. Chunking strategies

We implement and compare three chunking strategies:

- **Character-based** — `RecursiveCharacterTextSplitter`, splits on generic separators (paragraph/sentence/word), no awareness of document structure or meaning. Fast, cheap, works everywhere. Weakness: can cut a section or a formula in half.
- **Structure-based** — splits along the document's own structure (section headers like `3.2 Attention`, `3.2.1 Scaled Dot-Product Attention`). Keeps each section intact so a chunk is a coherent unit of the paper. Weakness: sections can be very uneven in length, and it only works when the structure is regular/detectable.
- **Semantic** — `SemanticChunker`, splits where the *embedding similarity* between consecutive sentences drops, i.e. where the topic actually shifts. Best topical coherence, but slower (needs an embedding call per sentence) and less predictable chunk sizes.

In production you'd pick one (or blend structure + semantic) based on how structured your documents are; here we build all three so you can compare retrieval quality later.
"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

char_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)
char_chunks = char_splitter.split_documents(docs)
print(f"Character-based chunks: {len(char_chunks)}")

import re
from langchain_core.documents import Document

def structure_based_split(documents, min_chunk_chars=200):
    """Split on section headers typical of academic papers, e.g. '3.2 Attention',
    '3.2.1 Scaled Dot-Product Attention'. Falls back to keeping small trailing
    text attached to the previous section rather than emitting tiny chunks."""
    full_text = "\n".join(d.page_content for d in documents)
    header_pattern = re.compile(r'(?m)^(\d+(\.\d+)*\s+[A-Z][^\n]{2,80})$')

    matches = list(header_pattern.finditer(full_text))
    if not matches:
        return [Document(page_content=full_text)]

    chunks = []
    for i, m in enumerate(matches):
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(full_text)
        section_title = m.group(1).strip()
        section_text = full_text[start:end].strip()
        if chunks and len(section_text) < min_chunk_chars:
            chunks[-1].page_content += "\n" + section_text
        else:
            chunks.append(Document(page_content=section_text, metadata={"section": section_title}))
    return chunks

structure_chunks = structure_based_split(docs)
print(f"Structure-based chunks: {len(structure_chunks)}")
for c in structure_chunks[:3]:
    print("---", c.metadata.get("section"), "| len:", len(c.page_content))

from langchain_experimental.text_splitter import SemanticChunker
from langchain_huggingface.embeddings import HuggingFaceEmbeddings

# Semantic chunking needs an embedding model to score topic shifts between sentences.
semantic_embed_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

semantic_splitter = SemanticChunker(
    semantic_embed_model,
    breakpoint_threshold_type="percentile",   # split at the biggest similarity drops
    breakpoint_threshold_amount=90,
)
semantic_chunks = semantic_splitter.split_documents(docs)
print(f"Semantic chunks: {len(semantic_chunks)}")

# Quick side-by-side comparison
print("Character-based:", len(char_chunks), "chunks | avg len:",
      sum(len(c.page_content) for c in char_chunks)//len(char_chunks))
print("Structure-based:", len(structure_chunks), "chunks | avg len:",
      sum(len(c.page_content) for c in structure_chunks)//len(structure_chunks))
print("Semantic:", len(semantic_chunks), "chunks | avg len:",
      sum(len(c.page_content) for c in semantic_chunks)//len(semantic_chunks))

# Pick which chunk set feeds the rest of the pipeline.
CHUNKS = char_chunks   # swap to structure_chunks / semantic_chunks to A/B test

"""## 3. Embedding model selection

Two signals drive the choice of embedding model:

1. **Language** — if the corpus (or the detected language of a sample of chunks) is not purely English, use a multilingual model. A monolingual English model embeds non-English text poorly, which silently degrades retrieval.
2. **Chunk size** — small chunks (a sentence or two) are well served by lightweight, fast models. Larger chunks (structure-based sections, which can run to several paragraphs) benefit from a model with a larger effective context and stronger representation power, since a small model's embedding becomes a lossy "average" of a long chunk.

This paper is English-only, so the multilingual branch won't trigger here — but the logic is written to generalize to mixed-language corpora.
"""

from langdetect import detect, DetectorFactory, LangDetectException
DetectorFactory.seed = 0

def detect_languages(chunks, sample_size=20):
    sample = chunks[:sample_size] if len(chunks) > sample_size else chunks
    langs = set()
    for c in sample:
        try:
            langs.add(detect(c.page_content))
        except LangDetectException:
            continue
    return langs

def select_embedding_model(chunks):
    langs = detect_languages(chunks)
    avg_len = sum(len(c.page_content) for c in chunks) / max(len(chunks), 1)
    is_multilingual = len(langs - {"en"}) > 0

    if is_multilingual:
        model_name = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
        reason = f"multiple languages detected ({langs}) -> multilingual model"
    elif avg_len > 1500:
        model_name = "BAAI/bge-base-en-v1.5"
        reason = f"large avg chunk size ({avg_len:.0f} chars) -> higher-capacity English model"
    else:
        model_name = "sentence-transformers/all-MiniLM-L6-v2"
        reason = f"short/medium English chunks (avg {avg_len:.0f} chars) -> fast lightweight model"

    print(f"Detected languages: {langs} | avg chunk len: {avg_len:.0f} chars")
    print(f"-> Selected embedding model: {model_name} ({reason})")
    return HuggingFaceEmbeddings(model_name=model_name), model_name

embedding_model, embedding_model_name = select_embedding_model(CHUNKS)

"""## 4. Vector store + keyword retriever (for hybrid search later)"""

from langchain_chroma import Chroma

vectordb = Chroma.from_documents(CHUNKS, embedding_model, persist_directory="/content/vectorDB")
vector_retriever = vectordb.as_retriever(search_type="similarity", search_kwargs={"k": 5})

from langchain_community.retrievers import BM25Retriever

# Keyword-based retriever, used for hybrid search alongside the vector retriever.
bm25_retriever = BM25Retriever.from_documents(CHUNKS)
bm25_retriever.k = 5

"""## 5. Query expansion

Very short queries (fewer than 3 words, e.g. "positional encoding") under-specify intent and often retrieve noisier chunks than a fuller question would. When that happens, we ask an LLM to rewrite the query into a fuller, self-contained question *before* retrieval, grounded only in generic domain rewriting (no hallucinated specifics).
"""

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate

expansion_llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

expansion_prompt = ChatPromptTemplate.from_template(
    """The user gave a very short search query for a document Q&A system: "{query}"
Rewrite it as a single, fuller, self-contained question that preserves the original intent.
Do not add facts or assumptions not implied by the original query. Return only the rewritten question."""
)

def expand_query_if_short(query: str, min_words: int = 3) -> str:
    if len(query.strip().split()) >= min_words:
        return query
    expanded = (expansion_prompt | expansion_llm).invoke({"query": query}).content.strip()
    print(f"Query expanded: '{query}' -> '{expanded}'")
    return expanded

"""## 6. Retrieval strategies: similarity, MMR, hybrid (with fallback)

- **Similarity search** — pure nearest-neighbor on embeddings. Good default, but can return several near-duplicate chunks.
- **MMR (Maximal Marginal Relevance)** — trades a bit of relevance for diversity, useful when the top results are redundant.
- **Hybrid (BM25 + vector, via `EnsembleRetriever`)** — combines keyword overlap with semantic similarity. Better when the query contains exact terms/numbers (e.g. "d_model 512") that dense embeddings can under-weight.

We try similarity first, check whether the top score clears a confidence threshold, and fall back to hybrid search if not.
"""

from langchain.retrievers import EnsembleRetriever

hybrid_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, vector_retriever],
    weights=[0.4, 0.6],
)

mmr_retriever = vectordb.as_retriever(search_type="mmr", search_kwargs={"k": 5, "fetch_k": 20})

def retrieve(query: str, score_threshold: float = 0.35):
    """Similarity search first; fall back to hybrid if the top match is weak.
    Chroma's relevance score is a distance -> lower is better, so we convert it
    to a 0-1 'confidence' where higher is better, and fall back below the threshold."""
    scored = vectordb.similarity_search_with_relevance_scores(query, k=5)
    top_score = scored[0][1] if scored else 0.0

    if top_score >= score_threshold:
        print(f"Similarity search sufficient (top score={top_score:.2f})")
        return [doc for doc, _ in scored]

    print(f"Similarity search weak (top score={top_score:.2f}) -> falling back to hybrid retrieval")
    return hybrid_retriever.invoke(query)

"""## 7. Reranking

Retrieval (vector/BM25/hybrid) optimizes for recall over a large candidate pool with a cheap similarity metric. A cross-encoder reranker scores each (query, chunk) pair jointly — much more accurate, but too slow to run over the whole corpus, so we only apply it to the small candidate set retrieval already narrowed down.
"""

from langchain_huggingface import HuggingFaceCrossEncoder
from langchain.retrievers.document_compressors import CrossEncoderReranker
from langchain.retrievers import ContextualCompressionRetriever

cross_encoder = HuggingFaceCrossEncoder(model_name="cross-encoder/ms-marco-MiniLM-L-6-v2")
reranker = CrossEncoderReranker(model=cross_encoder, top_n=3)

def retrieve_and_rerank(query: str):
    candidates = retrieve(query)
    reranked_retriever = ContextualCompressionRetriever(
        base_compressor=reranker,
        base_retriever=vectordb.as_retriever(search_kwargs={"k": len(candidates)}),
    )
    # Rerank against the already-fetched candidate pool rather than re-querying the whole index.
    scored = reranker.compress_documents(candidates, query)
    return scored

"""## 8. LLM experimentation

The original notebook's failure mode to guard against: the model ignoring the "answer only from context" instruction and using its own trained knowledge instead. We compare a couple of models on the same strict-context prompt and check whether each one (a) answers correctly when the context supports it, and (b) correctly says "no context found" when it doesn't.
"""

strict_prompt = ChatPromptTemplate.from_template(
    """You are an expert at answering questions strictly from the given context.
Do not use outside knowledge. If the context does not contain the answer, reply exactly: "no context found"

user query: {query}
context: {context}"""
)

def answer_with_llm(model_name: str, query: str, context: str) -> str:
    llm = ChatOpenAI(model=model_name, temperature=0)
    return (strict_prompt | llm).invoke({"query": query, "context": context}).content

def evaluate_llms(query: str, context: str, models=("gpt-4o-mini", "gpt-4.1-mini")):
    results = {}
    for m in models:
        results[m] = answer_with_llm(m, query, context)
    return results

# Sanity check: a query the context does NOT answer should trigger "no context found".
off_topic_check = answer_with_llm("gpt-4o-mini", "what is the capital of France?",
                                   "The Transformer uses multi-head attention.")
print("Off-topic guard check:", off_topic_check)

"""## 9. Caching

Two layers:

- **Exact-match cache** — LangChain's global LLM cache (SQLite-backed) avoids re-calling the API for an identical `(model, prompt)` pair. Cheap, but misses paraphrased repeats.
- **Semantic cache** — a small custom cache that embeds each query, and on a new query checks cosine similarity against past queries above a threshold. Catches "what's the formula for positional encoding" vs "positional encoding formula" as the same request.
"""

from langchain.globals import set_llm_cache
from langchain_community.cache import SQLiteCache

set_llm_cache(SQLiteCache(database_path="/content/llm_cache.db"))

import numpy as np

class SemanticCache:
    def __init__(self, embedding_model, threshold: float = 0.92):
        self.embedding_model = embedding_model
        self.threshold = threshold
        self.entries = []  # list of (embedding, query, answer)

    @staticmethod
    def _cosine(a, b):
        a, b = np.array(a), np.array(b)
        return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-10))

    def get(self, query: str):
        if not self.entries:
            return None
        q_emb = self.embedding_model.embed_query(query)
        best_score, best_answer = 0.0, None
        for emb, _, answer in self.entries:
            score = self._cosine(q_emb, emb)
            if score > best_score:
                best_score, best_answer = score, answer
        if best_score >= self.threshold:
            print(f"Semantic cache hit (similarity={best_score:.3f})")
            return best_answer
        return None

    def set(self, query: str, answer: str):
        q_emb = self.embedding_model.embed_query(query)
        self.entries.append((q_emb, query, answer))

semantic_cache = SemanticCache(embedding_model)

"""## 10. End-to-end pipeline"""

def rag_answer(query: str, model_name: str = "gpt-4o-mini"):
    cached = semantic_cache.get(query)
    if cached is not None:
        return cached

    expanded_query = expand_query_if_short(query)
    reranked_docs = retrieve_and_rerank(expanded_query)
    context = "\n".join(d.page_content for d in reranked_docs)

    answer = answer_with_llm(model_name, expanded_query, context)
    semantic_cache.set(query, answer)
    return answer

# Example run
print(rag_answer("positional encoding"))   # short query -> triggers expansion

# Re-run a paraphrase of the same question to see the semantic cache hit
print(rag_answer("what's the formula used for positional encodings"))